name: elessam_services
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  odoo_rpc: ^0.4.5
  geolocator: ^8.2.0
  get_storage: ^2.0.3
  intl: ^0.17.0
  flutter_launcher_icons: ^0.9.2
  # shared_preferences: ^2.0.13
  

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"

flutter: 
  uses-material-design: true

